name: publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - uses: actions/cache@v1
        with:
          path: gems
          key: gems-v1-${{ runner.OS }}-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            gems-v1-${{ runner.OS }}-${{ hashFiles('Gemfile.lock') }}
            gems-v1-${{ runner.OS }}-
      - run: bundle install --jobs=$(($(nproc)-1)) --path=gems
      - run: bundle exec rake build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
