name: publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 15 * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r7kamura/weneedfeed-action@v0.3.1
        with:
          base_url: https://r7kamura.github.io/weneedfeed-webace
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
